### PR TITLE
Restructure penalizing for bad metrics

### LINKED ISSUE #95: Restructure penalizing for bad metrics
**Refactor on which conditions are node penalized. New rules are:**

Node is penalized (_removed from active and set on initial cooldown_) if:
1) Fails to provide RPC response
2) Has not provided fresh ping (_in last 10 seconds_) - this is checked in the scheduled job

Node is removed from active nodes and not penalized if:
1) Last provided metrics are not valid (_lagging more than 10 blocks_) - this is checked in the scheduled job

Node is added to active if:
1) It is not set on cooldown (penalized) and the last provided metric is valid - this is checked in the metrics controller, and this in conjunction with #94 resolves the problem of restarting loadbalancer.
2) Scheduled check after node cooldown resolves node as active

### PR DESCRIPTION
**Pull request by MakMuftic**
**Refactor on which conditions are node penalized. New rules are:**

Node is penalized (_removed from active and set on initial cooldown_) if:
1) Fails to provide RPC response
2) Has not provided fresh ping (_in last 10 seconds_) - this is checked in the scheduled job

Node is removed from active nodes and not penalized if:
1) Last provided metrics are not valid (_lagging more than 10 blocks_) - this is checked in the scheduled job

Node is added to active if:
1) It is not set on cooldown (penalized) and the last provided metric is valid - this is checked in the metrics controller, and this in conjunction with #94 resolves the problem of restarting loadbalancer.
2) Scheduled check after node cooldown resolves node as active

### PR Checklist

- [x] I have run linter localy
- [x] I have run unit and integration tests locally
- [x] Rebased to master branch / merged master
- [x] Updated CHANGELOG.md

### Changes

- Refactored scheduled job to check separately for valid ping and valid metrics and penalizes nodes accordingly to new rules defined at the top + refactor unit tests
- Refactor `active` package to now support these utility functions: `CheckIfNodeActive`, `CheckIfPingActive`, `CheckIfMetricsValid`, `ActivateNodeIfReady` + refactor unit tests
- Refactor metrics `SaveMetricsHandler` to activate node if requirements met after on new metrics entry
- Start scheduled check for penalized nodes in new gorutine

### Issues

Closes #95

### CODE REVIEW

File: internal/active/active.go [hunk 1]
```diff
@@ -39,14 +59,37 @@ func CheckIfNodeActive(node models.Node, repos *repositories.Repos) (bool, error
...
 			latestBlockMetrics.BestBlockHeight, latestBlockMetrics.FinalizedBlockHeight,
 		)
 		return false, nil
 	}
-	
+
 	return true, nil
 }
+
+// ActivateNodeIfReady sets node to active nodes if latest metrics are valid and node is not penalized
```
Comment (mpetrun5) [inline internal/active/active.go]: adds node to active nodes :smile:

File: internal/schedule/checkactive/schedule.go [hunk 2]
```diff
@@ -36,15 +36,26 @@ func scheduledTask(repos *repositories.Repos, actions actions.Actions) {
...
+		}
+
+		metricsVald, err := active.CheckIfMetricsValid(node.ID, repos)
+		if err != nil {
+			log.Errorf("Unable to check if node %s active because of %v", node.ID, err)
+			continue
+		}
+
+		if !metricsVald {
+			_ = repos.NodeRepo.RemoveNodeFromActive(node)
```
Comment (mpetrun5) [inline internal/schedule/checkactive/schedule.go]: Maybe we should log this error

File: internal/active/active.go [hunk 3]
```diff
@@ -39,14 +59,37 @@ func CheckIfNodeActive(node models.Node, repos *repositories.Repos) (bool, error
...
+func ActivateNodeIfReady(nodeID string, repos repositories.Repos) error {
+	node, err := repos.NodeRepo.FindByID(nodeID)
```
Comment (mpetrun5) [inline internal/active/active.go]: Why not use IsNodeOnCooldown method here?

File: internal/active/active.go [hunk 4]
```diff
@@ -39,14 +59,37 @@ func CheckIfNodeActive(node models.Node, repos *repositories.Repos) (bool, error
...
+		return nil
+	}
+
+	metricsValid, err := CheckIfMetricsValid(nodeID, &repos)
+	if err != nil {
+		return err
+	}
+
+	if metricsValid {
+		_ = repos.NodeRepo.AddNodeToActive(*node)
```
Comment (mpetrun5) [inline internal/active/active.go]: Log?

**Review by mpetrun5 — COMMENTED** [review]
Metrics controller looks much cleaner now

File: internal/active/active.go (hunk 4 above)
Comment (mpetrun5) [reply internal/active/active.go]: if we add to active

File: internal/schedule/checkactive/schedule.go (hunk 2 above)
Comment (mpetrun5) [reply internal/schedule/checkactive/schedule.go]: And that we removed node from active

File: internal/active/active.go (hunk 3 above)
Comment (MakMuftic) [reply internal/active/active.go]: Because I needed `node` object for `AddNodeToActive`, but now I refactored `AddNodeToActive` and `RemoveNodeFromActive` to have for argument node ID (`string`) and not node struct. I also refactored this here to use `IsNodeOnCooldown`

File: internal/active/active.go (hunk 4 above)
Comment (MakMuftic) [reply internal/active/active.go]: :+1:

File: internal/schedule/checkactive/schedule.go (hunk 2 above)
Comment (MakMuftic) [reply internal/schedule/checkactive/schedule.go]: I agree

**Review by mpetrun5 — APPROVED** [review]
